version: "3.8"

services:
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_DB: meong
      POSTGRES_USER: jjj
      POSTGRES_PASSWORD: 1q2w3e4r!
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/meong
      SPRING_DATASOURCE_USERNAME: jjj
      SPRING_DATASOURCE_PASSWORD: 1q2w3e4r!
    networks:
      - backend-network

  # AI 서버 예시 (추가 예정)
  # ai:
  #   build: ./ai
  #   ports:
  #     - "8001:8001"
  #   networks:
  #     - backend-network

volumes:
  db-data:

networks:
  backend-network:
    driver: bridge
